---
.gitattributes:
  include:
    keys/private_key.pkcs7.pem: filter=git-crypt diff=git-crypt export-ignore
    .git-crypt: export-ignore
.rubocop.yml:
  default_configs:
    inherit_from: ".rubocop_todo.yml"
    AllCops:
      Include:
        - "rakelib/*.rake"
      Exclude:
        - ".modules/**/*"
    Style/SingleLineMethods:
      Exclude:
        - "rakelib/test.rake"
Rakefile:
  default_disabled_lint_checks:
    - '140chars'
Gemfile:
  required:
    ':system_tests':
      - gem: bolt
        git: https://github.com/h0tw1r3/bolt.git
        branch: h0tw1r3
      - gem: specinfra
        git: https://github.com/h0tw1r3/specinfra.git
        branch: fix-lxd-run
  overrides:
    - gem: puppetlabs_spec_helper
      version: '~> 7.0'
    - gem: puppet_litmus
      git: https://github.com/h0tw1r3/puppet_litmus.git
      branch: h0tw1r3
      platforms: [ 'ruby', 'x64_mingw' ]
.gitignore:
  paths:
    - .modules/
    - .resource_types/
    - bolt-debug.log
    - .plan_cache.json
    - .plugin_cache.json
    - .task_cache.json
    - .rerun.json
    - .terraform/
    - .terraform*lock.hcl
    - Puppetfile
.pdkignore:
  paths:
    - /provision.yaml
spec/default_facts.yml:
  delete: true
